"""Lilylet -> MIDI translation via MidiSeq2PrefixInTokenLevel (split-modality, lyl-in-token-level).

Split-modality sibling of tests/midi/gen_midiseq2_from_lilylet.py. Conditions on a lilylet score
and autoregressively generates the MIDI side as the self-describing **midiseq2** token language
(assets/midiseq2Vocab.yaml, vocab 582), but with a fundamentally different architecture:

  1. NO LYL ENCODER. The lilylet signal is NOT projected into a frozen encoder memory and scattered
     into a joint decoder. Instead, the raw lilylet patches (native width-16, vocab 256) are
     RE-EMBEDDED at the TOKEN-LEVEL decoder as prefix patches at NEGATIVE RoPE positions (-Kmax..-1),
     giving the within-patch token generator direct access to the relevant lilylet measures.

  2. SPLIT MODALITY. There is no joint [T,64] frame: lilylet stays at [Lp,16] and midi at [Mp,64],
     each in its own vocabulary. The patch-level decoder sees ONLY midi patches (midi-only
     windowed self-attention); the lilylet condition enters only at the token decoder as prefix.

  3. MEASURE-ID CROSS WINDOW. For each midi target patch, the lilylet patches in its cross window
     are gathered directly from measure ids (lyl_meas, midi_src, w_cross), not from a mask tensor —
     exactly as during training.

Full-recompute decode (NO KV cache): the midi self-attention decoder is windowed-causal, so this
is meant for SHORT scores. O(Mp^2) per step at the patch level + O((Kmax+P)^2) per token step.

Usage:
  python tests/midi/gen_midiseq2_prefixtl_from_lilylet.py --run <run_dir>      # 3 shortest .lyl
  python tests/midi/gen_midiseq2_prefixtl_from_lilylet.py --files a.lyl --device cuda
"""

import argparse
import glob
import os
import sys
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO_ROOT)

import torch
import torch.nn.functional as F

from starry.utils.config import Configuration
from starry.utils.model_factory import loadModel
from starry.lilylet.data.patchifier import LilyletTokenizer
from starry.midi.data.seq2CondSplitPachifier import (
	Midiseq2Tokenizer, EOM_ID, EOS_ID, BOS_ID, PAD_ID)
from starry.midi.data.condPatchifier import patchify_lilylet
from starry.midi.data.condPatchy import build_vis
from starry.lilylet.patchyGenerator import sample_next
from starry.bgpt import token_embedding_weight


RUN = os.path.expanduser('~/data/models/deep-starry-logs/midi/20260722-midi-measurewise-seq2split-prefixtl-nota0717-w4')
SRC_DIR = os.path.expanduser('~/work/lilylet/tests/output/notagenx-from-abc')
LYL_TOKENIZER = os.path.join(REPO_ROOT, 'assets', 'lilylet-tokenizer.json')
# Deterministic midiseq2 HEADER prompt (measure 0). Constant across the corpus: ticks_per_beat
# 0x1e0 (=480) rendered as nibble tokens `1 e 0`, and format_type 1. These become the measure-0
# seed patch(es); everything from measure 1 on is generated by the model.
DEFAULT_HEADER_TOKENS = ['ticks_per_beat', '1', 'e', '0', 'format_type', '1']


def load_model (run, checkpoint, device):
	'''Build MidiSeq2PrefixInTokenLevel from the run's .state.yaml and load weights (eval).

	Simpler than the joint MidiSeq2BgptSelfAttn loader: no lyl_encoder_weights hack needed — this
	model has no encoder. The checkpoint stores the deducer's state_dict directly.
	'''
	config = Configuration.createOrLoad(run, volatile=True)
	model = loadModel(config['model'], imports=config['imports'])
	blob = torch.load(checkpoint, map_location='cpu', weights_only=False)
	state = blob['model'] if isinstance(blob, dict) and 'model' in blob else blob
	missing, unexpected = model.load_state_dict(state, strict=False)
	if missing or unexpected:
		print(f'[load] {len(missing)} missing, {len(unexpected)} unexpected keys')
	return config, model.to(device).eval()


class PrefixTLMidiseq2Generator:
	'''Autoregressive midiseq2 generation conditioned on a fixed lilylet score via the
	MidiSeq2PrefixInTokenLevel model (split-modality, lyl-in-token-level).

	Architecture:
	  - Patch level: a midi-ONLY self-attention decoder (windowed-causal) runs over the growing
	    midi patch sequence; no lilylet enters at this level.
	  - Token level: for each new midi patch, the PrefixTokenLevelDecoder receives the patch hidden
	    state at position 0 and the relevant lilylet cross-window patches as prefix at negative
	    positions (-Kmax..-1), then generates tokens autoregressively (1..patch_size).
	'''

	def __init__ (self, model, lyl_tokenizer, seq2_tokenizer, config, device='cpu'):
		self.model = model
		self.lt = lyl_tokenizer
		self.st = seq2_tokenizer
		self.device = torch.device(device)
		self.patch_size = model.patch_size						# 64 (midi side)
		self.lyl_patch_size = model.lyl_patch_size				# 16 (lyl native)
		self.w_midi = int(config['data.args.w_midi'] or 4)
		self.w_cross = model.w_cross							# from model (default 1)
		# midiseq2 special ids.
		self.pad_id, self.bos_id, self.eos_id, self.eom_id = PAD_ID, BOS_ID, EOS_ID, EOM_ID

	def _additive_mask (self, allowed, dtype):
		'''Convert a bool allow-mask to an additive mask accepted consistently by HF backends.

		Some Llama eager-attention paths add a 4D mask to attention scores, while SDPA treats a
		bool mask as an allow-mask. Using the additive form avoids backend-dependent semantics.
		'''
		return torch.zeros_like(allowed, dtype=dtype).masked_fill(
			~allowed, torch.finfo(dtype).min)

	def _build_midi_mask (self, midi_meas):
		'''Build the [1,1,Mp,Mp] midi-only windowed causal mask from midi measure ids.

		Uses build_vis with all modality=1, own=midi_meas, src=midi_meas (identity alignment; the
		cross block is empty since there's no modality-0). This exactly matches training.
		'''
		Mp = len(midi_meas)
		mod = torch.ones(Mp, dtype=torch.long)
		own = torch.tensor(midi_meas, dtype=torch.long)
		vis = build_vis(mod, own, own, self.w_midi, self.w_cross)       # [Mp,Mp]
		return vis.unsqueeze(0).unsqueeze(0).to(self.device)            # [1,1,Mp,Mp]

	def _gather_prefix (self, src_measure):
		'''Gather the lyl cross-window patches for a target with source measure `src_measure`.

		Cross rule (matching _gather_lyl_prefix in the model):
		  valid = real & (lyl_meas==0 (header) | (src!=0 & lyl_meas > src-w_cross & lyl_meas <= src))

		Returns (prefix_embeds [1,K,d], prefix_mask [1,K]) or (None, None) if no valid lyl patches.
		'''
		lm = self._lyl_meas												# [Lp]
		Lp = lm.shape[0]
		if Lp == 0:
			return None, None
		s = src_measure
		header = (lm == 0)
		if s == 0:
			# midi header patch: only lyl header (measure 0) is visible
			valid = header
		else:
			in_window = (lm > s - self.w_cross) & (lm <= s)
			valid = header | in_window
		if not valid.any():
			return None, None

		# gather valid lyl patch ids, right-aligned into [1, K, lyl_patch_size]
		idx = torch.nonzero(valid, as_tuple=False).flatten()			# [K]
		K = idx.shape[0]
		lyl_ids = self._lyl_patches[idx]								# [K, lyl_patch_size]
		prefix_embeds = self.model._embed_lyl_prefix(lyl_ids.unsqueeze(0))	# [1,K,d_model]
		prefix_mask = torch.ones(1, K, dtype=torch.long, device=self.device)
		return prefix_embeds, prefix_mask

	@torch.no_grad()
	def _decode_patch (self, hidden, prefix_embeds, prefix_mask,
		temperature, top_k, top_p, rep_penalty=1.0, rep_context=None):
		'''Token-level autoregressive generation of ONE midiseq2 patch.

		Replicates PrefixTokenLevelDecoder.forward but step-by-step (no KV cache, full recompute):
		  sequence = [prefix_embeds(-Kmax..-1), hidden(0), tok_1(1), ..., tok_t(t)]
		  4D mask: causal & key_valid | self-diagonal (matching training exactly)

		Stops on: <pad> (after >=1 token), <eom> (measure close), or patch_size tokens reached.
		Returns a list of patch_size int ids (right-padded with <pad>).
		'''
		dec = self.model.token_level_decoder.base
		wte = token_embedding_weight(dec)
		Kmax = prefix_embeds.shape[1] if prefix_embeds is not None else 0

		generated = []
		# initial input: [prefix..., hidden]
		if Kmax > 0:
			emb = torch.cat((prefix_embeds, hidden.reshape(1, 1, -1)), dim=1)	# [1,Kmax+1,h]
		else:
			emb = hidden.reshape(1, 1, -1)									# [1,1,h]

		while len(generated) < self.patch_size:
			S = emb.shape[1]
			# position_ids: [-Kmax..-1, 0, 1, ..., t]
			if Kmax > 0:
				prefix_pos = torch.arange(-Kmax, 0, device=self.device)
				midi_pos = torch.arange(0, S - Kmax, device=self.device)
				position_ids = torch.cat((prefix_pos, midi_pos)).unsqueeze(0)	# [1,S]
			else:
				position_ids = torch.arange(0, S, device=self.device).unsqueeze(0)

			# 4D causal mask: causal & key_valid | self-diagonal
			idx = torch.arange(S, device=self.device)
			causal = idx.unsqueeze(0) <= idx.unsqueeze(1)					# [S,S]
			if Kmax > 0 and prefix_mask is not None:
				key_valid_vec = torch.cat((prefix_mask[0].bool(),
					torch.ones(S - Kmax, dtype=torch.bool, device=self.device)))
			else:
				key_valid_vec = torch.ones(S, dtype=torch.bool, device=self.device)
			mask4d = (causal & key_valid_vec.unsqueeze(0))					# [S,S]
			mask4d = mask4d | torch.eye(S, dtype=torch.bool, device=self.device)
			mask4d = self._additive_mask(mask4d, emb.dtype).unsqueeze(0).unsqueeze(0) # [1,1,S,S]

			logits = dec(inputs_embeds=emb, attention_mask=mask4d,
				position_ids=position_ids).logits[0, -1]

			if rep_penalty and rep_penalty != 1.0 and rep_context:
				logits = logits.clone()
				ids = torch.tensor(sorted(rep_context), device=self.device)
				sel = logits[ids]
				logits[ids] = torch.where(sel > 0, sel / rep_penalty, sel * rep_penalty)

			nxt = sample_next(logits, temperature=temperature, top_k=top_k, top_p=top_p)

			# first <pad> ends the patch (right-pad the rest)
			if nxt == self.pad_id and generated:
				generated += [self.pad_id] * (self.patch_size - len(generated))
				break
			generated.append(nxt)
			# <eom> closes the measure: pad the tail and stop
			if nxt == self.eom_id:
				generated += [self.pad_id] * (self.patch_size - len(generated))
				break
			if len(generated) >= self.patch_size:
				break
			# append the new token's embedding for the next step
			tok = torch.tensor([[nxt]], device=self.device)
			emb = torch.cat((emb, F.embedding(tok, wte)), dim=1)

		return generated

	def _seed_header (self, header_tokens):
		'''Build the measure-0 header seed patch(es) from token strings (chunked to patch_size).'''
		ids = self.st.token_ids(header_tokens)
		patches = []
		for start in range(0, len(ids), self.patch_size):
			chunk = ids[start:start + self.patch_size]
			chunk = chunk + [self.pad_id] * (self.patch_size - len(chunk))
			patches.append(chunk)
		return patches or [[self.pad_id] * self.patch_size]

	@torch.no_grad()
	def generate (self, lyl_text, header_tokens=None, max_midi_patches=2048, max_measures=0,
		temperature=1.0, top_k=0, top_p=0.9, rep_penalty=1.0, rep_window=8, verbose=False):
		'''Generate a whole-song midiseq2 text string conditioned on `lyl_text`.

		header_tokens: midiseq2 header token strings (measure 0). max_measures: stop after this
		many <eom>-closed measures (0 = only stop on <eos> / max_midi_patches).
		'''
		header_tokens = DEFAULT_HEADER_TOKENS if header_tokens is None else header_tokens

		# --- fixed lilylet prefix: patchified at native width-16, stored as tensors ---
		lyl_patches16, lyl_meas_list = patchify_lilylet(lyl_text, self.lt, patch_size=self.lyl_patch_size)
		Lp = len(lyl_patches16)
		self._lyl_patches = torch.tensor(lyl_patches16, dtype=torch.long, device=self.device)	# [Lp,16]
		self._lyl_meas = torch.tensor(lyl_meas_list, dtype=torch.long, device=self.device)		# [Lp]

		# --- midi seed: deterministic header patch(es) (measure 0), never re-predicted ---
		midi_patches = self._seed_header(header_tokens)
		midi_meas = [0] * len(midi_patches)						# header → measure 0
		midi_src = [0] * len(midi_patches)						# header → source measure 0
		gen_tokens = list(header_tokens)						# flat token stream for output

		cur_measure = 1											# first body patch is measure 1
		steps = 0
		stop = None
		while len(midi_patches) < max_midi_patches:
			Mp = len(midi_patches)
			# --- patch-level: midi-only self-attention decoder ---
			patches_t = torch.tensor([midi_patches], dtype=torch.long, device=self.device)		# [1,Mp,64]
			embeds = self.model._midi_embed(patches_t)											# [1,Mp,d]
			midi_mask = self._build_midi_mask(midi_meas)										# [1,1,Mp,Mp]
			positions = torch.arange(Mp, device=self.device).unsqueeze(0)						# [1,Mp]
			dec_out = self.model.decoder(inputs_embeds=embeds, attention_mask=midi_mask,
				position_ids=positions)['last_hidden_state']
			hidden = dec_out[0, -1]															# [d_model]

			# --- token-level: gather lyl prefix for this target, then decode ---
			prefix_embeds, prefix_mask = self._gather_prefix(cur_measure)

			rep_context = None
			if rep_penalty and rep_penalty != 1.0:
				rep_context = {t for p in midi_patches[-rep_window:] for t in p
					if t not in (self.pad_id, self.bos_id, self.eos_id, self.eom_id)}

			patch_ids = self._decode_patch(hidden, prefix_embeds, prefix_mask,
				temperature, top_k, top_p, rep_penalty=rep_penalty, rep_context=rep_context)
			steps += 1

			# <eos> patch [bos, eos, ...] → stop
			if patch_ids[0] == self.bos_id and patch_ids[1] == self.eos_id:
				stop = 'eos'
				break

			midi_patches.append(patch_ids)
			midi_meas.append(cur_measure)
			midi_src.append(cur_measure)

			# render this patch's non-pad tokens into the output stream
			toks = [self.st.tokens[i] for i in patch_ids if i != self.pad_id]
			gen_tokens += toks
			if verbose:
				print('  m%d: %s' % (cur_measure, ' '.join(toks)))

			# an <eom> anywhere in the patch closes the current measure
			if self.eom_id in patch_ids:
				cur_measure += 1
				if max_measures and cur_measure > max_measures:
					stop = 'max_measures'
					break
		if stop is None:
			stop = 'max_patches'

		text = self._render(gen_tokens)
		return text, dict(stop=stop, steps=steps, midi_patches=len(midi_patches),
			measures=cur_measure - 1, lyl_patches=Lp)

	def _render (self, tokens):
		'''Render the flat token stream into midiseq2 text: a newline at each <eom> (measure
		break) so the output reads measure-per-block and round-trips through parse_events.'''
		lines, cur = [], []
		for t in tokens:
			if t == '<eom>':
				lines.append(' '.join(cur)); cur = []
			elif t == '<eos>':
				continue
			else:
				cur.append(t)
		if cur:
			lines.append(' '.join(cur))
		return '\n'.join(lines) + '\n'


def _pick_sources (files, src_dir, num):
	'''Resolve explicit --files or default to the `num` SHORTEST .lyl in src_dir.'''
	if files:
		out = []
		for f in files:
			out.append(f if os.path.isabs(f) or os.path.exists(f) else os.path.join(src_dir, f))
		return out
	allf = glob.glob(os.path.join(src_dir, '*.lyl'))
	allf.sort(key=lambda p: os.path.getsize(p))
	return allf[:num]


def main ():
	ap = argparse.ArgumentParser()
	ap.add_argument('--run', default=RUN, help='training run dir (best.chkpt + .state.yaml)')
	ap.add_argument('--checkpoint', default=None, help='checkpoint path (default: <run>/best.chkpt)')
	ap.add_argument('--src-dir', default=SRC_DIR, help='dir of source .lyl files')
	ap.add_argument('--files', nargs='*', default=None,
		help='specific .lyl files (abs, or names under --src-dir); default: shortest N')
	ap.add_argument('--num', type=int, default=3, help='how many shortest .lyl to use when --files omitted')
	ap.add_argument('--max-midi-patches', type=int, default=4096)
	ap.add_argument('--max-measures', type=int, default=0, help='stop after N measures (0 = until <eos>)')
	ap.add_argument('--temperature', type=float, default=1.0)
	ap.add_argument('--top-k', type=int, default=0)
	ap.add_argument('--top-p', type=float, default=0.9)
	ap.add_argument('--rep-penalty', type=float, default=1.0,
		help='CTRL-style repetition penalty (>1 discourages recently-emitted tokens; 1.0 = off)')
	ap.add_argument('--rep-window', type=int, default=8,
		help='number of recent patches contributing to the repetition-penalty token set')
	ap.add_argument('--seed', type=int, default=0)
	ap.add_argument('--threads', type=int, default=14)
	ap.add_argument('--device', default='cpu')
	ap.add_argument('--out-dir', default=os.path.join(REPO_ROOT, 'tests', 'output', 'midiseq2_prefixtl_from_lilylet'))
	ap.add_argument('--verbose', action='store_true')
	args = ap.parse_args()

	torch.set_num_threads(args.threads)
	device = args.device if (args.device != 'cuda' or torch.cuda.is_available()) else 'cpu'
	if device != args.device:
		print('[warn] cuda unavailable, falling back to cpu')

	ckpt = args.checkpoint or os.path.join(args.run, 'best.chkpt')
	assert os.path.isfile(ckpt), f'checkpoint not found: {ckpt}'
	config, model = load_model(args.run, ckpt, device)
	n_params = sum(p.numel() for p in model.parameters())
	print('run:', args.run)
	print('checkpoint:', ckpt)
	print('params: %.2fM | d_model %d | patch_size %d | lyl_patch_size %d | w_midi %s w_cross %s | device %s'
		% (n_params / 1e6, config['model.args.d_model'], model.patch_size, model.lyl_patch_size,
			config['data.args.w_midi'], model.w_cross, device))

	lt = LilyletTokenizer(LYL_TOKENIZER)
	st = Midiseq2Tokenizer()
	gen = PrefixTLMidiseq2Generator(model, lt, st, config, device=device)

	sources = _pick_sources(args.files, args.src_dir, args.num)
	assert sources, 'no source .lyl files found'
	os.makedirs(args.out_dir, exist_ok=True)
	print('\n--- %d source(s) (temp=%.2f top_k=%d top_p=%.2f max_patches=%d max_measures=%s) ---'
		% (len(sources), args.temperature, args.top_k, args.top_p, args.max_midi_patches, args.max_measures))

	for i, src in enumerate(sources):
		torch.manual_seed(args.seed)
		with open(src, encoding='utf-8') as f:
			lyl_text = f.read()
		name = os.path.splitext(os.path.basename(src))[0]
		print('\n===== [%d/%d] %s (%d bytes) =====' % (i + 1, len(sources), name, len(lyl_text)))
		t0 = time.perf_counter()
		text, info = gen.generate(lyl_text, max_midi_patches=args.max_midi_patches,
			max_measures=args.max_measures, temperature=args.temperature,
			top_k=args.top_k, top_p=args.top_p,
			rep_penalty=args.rep_penalty, rep_window=args.rep_window, verbose=args.verbose)
		dt = time.perf_counter() - t0
		out = os.path.join(args.out_dir, name + '.midiseq2.txt')
		with open(out, 'w', encoding='utf-8') as f:
			f.write(text)
		# sanity: the generated midiseq2 text should parse back into absolute-tick events
		_, events = st.parse_events(text)
		print('[%s] %.1fs | lyl_patches %d | midi_patches %d | measures %d'
			% (info['stop'], dt, info['lyl_patches'], info['midi_patches'], info['measures']))
		print('  parse_events: %d events -> %s' % (len(events), out))


if __name__ == '__main__':
	main()
