"""Lilylet -> MIDI translation via MidiSeq2BgptSelfAttn (midiseq2 variant).

midiseq2 sibling of tests/midi/gen_midi_from_lilylet.py. Conditions on a lilylet score (a
READ-ONLY prefix encoded once by the frozen lyl encoder) and autoregressively generates the
MIDI side as the self-describing **midiseq2** token language (assets/midiseq2Vocab.yaml, vocab
838), under the SAME measure-coupled windowed/block joint attention mask the Seq2CondMidiPatchy
feeder builds (build_vis). Two things differ from the basic-MIDI base:

  1. DUAL WIDTH. The joint patch frame is patch_size=64 wide; lilylet ids occupy columns
     [0, lyl_patch_size=16) (<pad> tail) and midiseq2 ids use the full 64. So the lilylet prefix
     is patchified at width 16 (fed to the frozen encoder) and LEFT-ALIGNED into the 64-wide
     joint frame, while the midi side embeds the full 64 columns — mirroring the model's forward.

  2. MEASURE-CHUNKED midiseq2 patches with a SUPERVISED terminator. A measure is one variable-
     length midiseq2 token run ending in an <eom> TOKEN (id 4), chunked into 64-wide patches
     (only the measure's LAST patch is <pad>-padded; interior patches are full 64). Unlike the
     basic path — whose event patches ended at an UNSUPERVISED <pad> (the free-run collapse in
     gen_midi_from_lilylet's docstring) — here <eom> is a real supervised token, so the model
     learns to close measures. Generation watches for <eom> (advance measure) and the whole-song
     <eos> patch ([<bos>, <eos>, ...], stop).

Full-recompute decode (NO KV cache): the joint self-attention mask is windowed, not plain causal,
and the decoder is O(T^2), so this is meant for SHORT scores.

Usage:
  python tests/midi/gen_midiseq2_from_lilylet.py --run <run_dir>          # 3 shortest .lyl
  python tests/midi/gen_midiseq2_from_lilylet.py --files a.lyl --device cuda
"""

import argparse
import glob
import os
import sys
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO_ROOT)

import torch
import torch.nn.functional as F

from starry.utils.config import Configuration
from starry.utils.model_factory import loadModel
from starry.lilylet.data.patchifier import LilyletTokenizer
from starry.midi.data.seq2CondPachifier import (
	Midiseq2Tokenizer, patchify_lilylet, PATCH_SIZE, EOM_ID, EOS_ID, BOS_ID, PAD_ID)
from starry.midi.data.condPatchy import build_vis
from starry.lilylet.patchyGenerator import sample_next
from starry.bgpt import token_embedding_weight


RUN = os.path.expanduser('~/data/models/deep-starry-logs/midi/20260717-midi-measurewise-seq2-selfattn-nota0717-w4')
SRC_DIR = os.path.expanduser('~/work/lilylet/tests/output/notagenx-from-abc')
LYL_TOKENIZER = os.path.join(REPO_ROOT, 'assets', 'lilylet-tokenizer.json')
# Deterministic midiseq2 HEADER prompt (measure 0). Constant across the corpus: ticks_per_beat
# 0x1e0 (=480) rendered as nibble tokens `1 e 0`, and format_type 1. These become the measure-0
# seed patch(es); everything from measure 1 on is generated by the model.
DEFAULT_HEADER_TOKENS = ['ticks_per_beat', '1', 'e', '0', 'format_type', '1']


def load_model (run, checkpoint, device):
	'''Build MidiSeq2BgptSelfAttn from the run's .state.yaml and load weights (eval).

	lyl_encoder_weights points at a remote training path that need not exist here; the encoder
	tensors come from THIS checkpoint anyway, so blank it to skip the load attempt.
	'''
	config = Configuration.createOrLoad(run, volatile=True)
	config['model.args.lyl_encoder_weights'] = None
	model = loadModel(config['model'], imports=config['imports'])
	blob = torch.load(checkpoint, map_location='cpu', weights_only=False)
	state = blob['model'] if isinstance(blob, dict) and 'model' in blob else blob
	# the checkpoint stores the deducer's state_dict directly (no 'deducer.' prefix).
	missing, unexpected = model.load_state_dict(state, strict=False)
	if missing or unexpected:
		print(f'[load] {len(missing)} missing, {len(unexpected)} unexpected keys')
	return config, model.to(device).eval()


class Midiseq2FromLilyletGenerator:
	'''Autoregressive midiseq2 generation conditioned on a fixed lilylet score.

	The lilylet prefix is a read-only condition: its width-16 patches occupy joint positions
	[0, L) (widened to 64 with a <pad> tail) with modality 0 and RoPE positions 0..L-1. Generated
	midiseq2 patches occupy positions L.. with modality 1 and their OWN RoPE frame (0..Mp-1). At
	every step the full joint sequence is re-encoded (no KV cache) and the windowed/block mask is
	rebuilt from the per-patch own/src measure tags, so the coupling matches training exactly.
	'''

	def __init__ (self, model, lyl_tokenizer, seq2_tokenizer, config, device='cpu'):
		self.model = model
		self.lt = lyl_tokenizer
		self.st = seq2_tokenizer
		self.device = torch.device(device)
		self.patch_size = model.patch_size						# 64 (midi side)
		self.lyl_patch_size = model.lyl_patch_size				# 16 (encoder slice)
		self.w_midi = int(config['data.args.w_midi'] or 2)
		self.w_cross = int(config['data.args.w_cross'] or 2)
		# midiseq2 special ids (from the vocab asset).
		self.pad_id, self.bos_id, self.eos_id, self.eom_id = PAD_ID, BOS_ID, EOS_ID, EOM_ID

	def _widen (self, lyl_patch16):
		'''Left-align a width-16 lilylet patch into the 64-wide joint frame (<pad> tail).'''
		return list(lyl_patch16) + [self.lt.pad_id] * (self.patch_size - self.lyl_patch_size)

	@torch.no_grad()
	def _encode_lyl (self, lyl_patches16):
		'''Encode the lilylet prefix into projected memory [1, L, d_model] (done once).

		Feeds ONLY the width-16 lilylet patches to the frozen encoder (its patch_embedding is
		16*256 wide), mirroring MidiSeq2BgptSelfAttn.forward's [:, :, :lyl_patch_size] slice.
		'''
		L = len(lyl_patches16)
		patches = torch.tensor([lyl_patches16], dtype=torch.long, device=self.device)	# [1,L,16]
		real = torch.ones(1, L, dtype=torch.long, device=self.device)
		pos = torch.arange(L, device=self.device).unsqueeze(0)							# [1,L]
		memory = self.model.lyl_encoder(patches, real, position_ids=pos)['last_hidden_state']
		return self.model.enc_proj(memory)												# [1,L,d_model]

	@torch.no_grad()
	def _decode_patch (self, hidden, temperature, top_k, top_p, rep_penalty=1.0, rep_context=None):
		'''Token-level decode of ONE midiseq2 patch (up to patch_size tokens) from its patch
		hidden state.

		Position 0 is the patch hidden state (not an embedding); positions 1.. are the embeddings
		of the tokens sampled so far. A patch terminates at the first <pad> (id 0) after >=1 token,
		at an <eom> (id 4, measure close), or at patch_size tokens (measure continues into the next
		patch). Unlike the basic path, <eom> is a SUPERVISED token — the model learns to emit it —
		so measure termination is learned, not an unsupervised <pad> artifact.

		rep_penalty / rep_context: optional CTRL-style repetition penalty (>1 damps recently-emitted
		content token ids); 1.0 disables. Kept for parity with the basic generator; midiseq2's
		supervised <eom> usually makes it unnecessary.
		'''
		dec = self.model.token_level_decoder.base
		wte = token_embedding_weight(dec)
		generated = []
		emb = hidden.reshape(1, 1, -1)
		while len(generated) < self.patch_size:
			logits = dec(inputs_embeds=emb).logits[0, -1]
			if rep_penalty and rep_penalty != 1.0 and rep_context:
				logits = logits.clone()
				ids = torch.tensor(sorted(rep_context), device=self.device)
				sel = logits[ids]
				logits[ids] = torch.where(sel > 0, sel / rep_penalty, sel * rep_penalty)
			nxt = sample_next(logits, temperature=temperature, top_k=top_k, top_p=top_p)
			# first <pad> ends the patch; right-pad the rest (matches the chunk-padded layout).
			if nxt == self.pad_id and generated:
				generated += [self.pad_id] * (self.patch_size - len(generated))
				break
			generated.append(nxt)
			# <eom> closes the measure: pad the patch tail (as _chunk_measure does) and stop early.
			if nxt == self.eom_id:
				generated += [self.pad_id] * (self.patch_size - len(generated))
				break
			if len(generated) >= self.patch_size:
				break
			tok = torch.tensor([[nxt]], device=self.device)
			emb = torch.cat((emb, F.embedding(tok, wte)), dim=1)
		return generated

	def _seed_header (self, header_tokens):
		'''Build the measure-0 header seed patch(es) from token strings (chunked to patch_size).'''
		ids = self.st.token_ids(header_tokens)
		patches = []
		for start in range(0, len(ids), self.patch_size):
			chunk = ids[start:start + self.patch_size]
			chunk = chunk + [self.pad_id] * (self.patch_size - len(chunk))
			patches.append(chunk)
		return patches or [[self.pad_id] * self.patch_size]

	@torch.no_grad()
	def generate (self, lyl_text, header_tokens=None, max_midi_patches=2048, max_measures=0,
		temperature=1.0, top_k=0, top_p=0.9, rep_penalty=1.0, rep_window=8, verbose=False):
		'''Generate a whole-song midiseq2 text string conditioned on `lyl_text`.

		header_tokens: midiseq2 header token strings (measure 0). max_measures: stop after this
		many <eom>-closed measures (0 = only stop on <eos> / max_midi_patches).
		'''
		header_tokens = DEFAULT_HEADER_TOKENS if header_tokens is None else header_tokens

		# --- fixed lilylet prefix: width-16 patches + measure tags, encoded once ---
		lyl_patches16, lyl_meas = patchify_lilylet(lyl_text, self.lt, patch_size=self.lyl_patch_size)
		L = len(lyl_patches16)
		lyl_wide = [self._widen(p) for p in lyl_patches16]			# 64-wide joint frame
		memory = self._encode_lyl(lyl_patches16)					# [1,L,d_model]

		# --- midi seed: deterministic header patch(es) (measure 0), never re-predicted ---
		midi_patches = self._seed_header(header_tokens)
		midi_own = [0] * len(midi_patches)							# header -> measure 0
		gen_tokens = list(header_tokens)							# flat token stream for output

		wte_dtype = self.model.enc_proj.weight.dtype
		cur_measure = 1												# first body patch is measure 1
		steps = 0
		stop = None
		while len(midi_patches) < max_midi_patches:
			# assemble the joint sequence: [lyl prefix (64-wide) ; midi (header + body so far)]
			joint_patches = lyl_wide + midi_patches
			T = len(joint_patches)
			patches = torch.tensor([joint_patches], dtype=torch.long, device=self.device).reshape(1, T, self.patch_size)
			positions = torch.zeros(1, T, dtype=torch.long, device=self.device)
			positions[0, :L] = torch.arange(L, device=self.device)
			positions[0, L:] = torch.arange(T - L, device=self.device)
			modality = torch.zeros(T, dtype=torch.long, device=self.device)
			modality[L:] = 1
			own = torch.tensor(lyl_meas + midi_own, dtype=torch.long, device=self.device)
			# identity alignment (source_measure == index, as on the sibling corpus): src == own.
			vis = build_vis(modality, own, own, self.w_midi, self.w_cross)			# [T,T]
			attn_mask = vis.unsqueeze(0).unsqueeze(0)								# [1,1,T,T]

			# joint embedding: midi-embed the full 64 width everywhere, then overwrite the lyl
			# prefix positions with the projected encoder memory (exactly as forward does).
			embeds = self.model._midi_embed(patches)								# [1,T,d_model]
			embeds[:, :L] = memory.to(wte_dtype)
			dec = self.model.decoder(inputs_embeds=embeds, attention_mask=attn_mask,
				position_ids=positions)['last_hidden_state']

			# content repetition penalty over the last rep_window patches (drop structural ids).
			rep_context = None
			if rep_penalty and rep_penalty != 1.0:
				rep_context = {t for p in midi_patches[-rep_window:] for t in p
					if t not in (self.pad_id, self.bos_id, self.eos_id, self.eom_id)}
			patch_ids = self._decode_patch(dec[0, -1], temperature, top_k, top_p,
				rep_penalty=rep_penalty, rep_context=rep_context)
			steps += 1

			# <eos> patch [bos, eos, ...] -> stop
			if patch_ids[0] == self.bos_id and patch_ids[1] == self.eos_id:
				stop = 'eos'
				break

			midi_patches.append(patch_ids)
			midi_own.append(cur_measure)
			# render this patch's non-pad tokens into the output stream
			toks = [self.st.tokens[i] for i in patch_ids if i != self.pad_id]
			gen_tokens += toks
			if verbose:
				print('  m%d: %s' % (cur_measure, ' '.join(toks)))

			# an <eom> anywhere in the patch closes the current measure and advances.
			if self.eom_id in patch_ids:
				cur_measure += 1
				if max_measures and cur_measure > max_measures:
					stop = 'max_measures'
					break
		if stop is None:
			stop = 'max_patches'

		text = self._render(gen_tokens)
		return text, dict(stop=stop, steps=steps, midi_patches=len(midi_patches),
			measures=cur_measure - 1, lyl_patches=L)

	def _render (self, tokens):
		'''Render the flat token stream into midiseq2 text: a newline at each <eom> (measure
		break) so the output reads measure-per-block and round-trips through parse_events (which
		treats <eom>/<eos> as stray tokens and skips them). <eos> is dropped.'''
		lines, cur = [], []
		for t in tokens:
			if t == '<eom>':
				lines.append(' '.join(cur)); cur = []
			elif t == '<eos>':
				continue
			else:
				cur.append(t)
		if cur:
			lines.append(' '.join(cur))
		return '\n'.join(lines) + '\n'


def _pick_sources (files, src_dir, num):
	'''Resolve explicit --files or default to the `num` SHORTEST .lyl in src_dir (short = fewer
	patches = a smaller O(T^2) joint sequence, so the CPU test stays quick).'''
	if files:
		out = []
		for f in files:
			out.append(f if os.path.isabs(f) or os.path.exists(f) else os.path.join(src_dir, f))
		return out
	allf = glob.glob(os.path.join(src_dir, '*.lyl'))
	allf.sort(key=lambda p: os.path.getsize(p))
	return allf[:num]


def main ():
	ap = argparse.ArgumentParser()
	ap.add_argument('--run', default=RUN, help='training run dir (best.chkpt + .state.yaml)')
	ap.add_argument('--checkpoint', default=None, help='checkpoint path (default: <run>/best.chkpt)')
	ap.add_argument('--src-dir', default=SRC_DIR, help='dir of source .lyl files')
	ap.add_argument('--files', nargs='*', default=None,
		help='specific .lyl files (abs, or names under --src-dir); default: shortest N')
	ap.add_argument('--num', type=int, default=3, help='how many shortest .lyl to use when --files omitted')
	ap.add_argument('--max-midi-patches', type=int, default=4096)
	ap.add_argument('--max-measures', type=int, default=0, help='stop after N measures (0 = until <eos>)')
	ap.add_argument('--temperature', type=float, default=1.0)
	ap.add_argument('--top-k', type=int, default=0)
	ap.add_argument('--top-p', type=float, default=0.9)
	ap.add_argument('--rep-penalty', type=float, default=1.0,
		help='CTRL-style repetition penalty (>1 discourages recently-emitted tokens; 1.0 = off)')
	ap.add_argument('--rep-window', type=int, default=8,
		help='number of recent patches contributing to the repetition-penalty token set')
	ap.add_argument('--seed', type=int, default=0)
	ap.add_argument('--threads', type=int, default=14)
	ap.add_argument('--device', default='cpu')
	ap.add_argument('--out-dir', default=os.path.join(REPO_ROOT, 'tests', 'output', 'midiseq2_from_lilylet'))
	ap.add_argument('--verbose', action='store_true')
	args = ap.parse_args()

	torch.set_num_threads(args.threads)
	device = args.device if (args.device != 'cuda' or torch.cuda.is_available()) else 'cpu'
	if device != args.device:
		print('[warn] cuda unavailable, falling back to cpu')

	ckpt = args.checkpoint or os.path.join(args.run, 'best.chkpt')
	assert os.path.isfile(ckpt), f'checkpoint not found: {ckpt}'
	config, model = load_model(args.run, ckpt, device)
	n_params = sum(p.numel() for p in model.parameters())
	print('run:', args.run)
	print('checkpoint:', ckpt)
	print('params: %.2fM | d_model %d | patch_size %d | lyl_patch_size %d | w_midi %s w_cross %s | device %s'
		% (n_params / 1e6, config['model.args.d_model'], model.patch_size, model.lyl_patch_size,
			config['data.args.w_midi'], config['data.args.w_cross'], device))

	lt = LilyletTokenizer(LYL_TOKENIZER)
	st = Midiseq2Tokenizer()
	gen = Midiseq2FromLilyletGenerator(model, lt, st, config, device=device)

	sources = _pick_sources(args.files, args.src_dir, args.num)
	assert sources, 'no source .lyl files found'
	os.makedirs(args.out_dir, exist_ok=True)
	print('\n--- %d source(s) (temp=%.2f top_k=%d top_p=%.2f max_patches=%d max_measures=%s) ---'
		% (len(sources), args.temperature, args.top_k, args.top_p, args.max_midi_patches, args.max_measures))

	for i, src in enumerate(sources):
		torch.manual_seed(args.seed)
		with open(src, encoding='utf-8') as f:
			lyl_text = f.read()
		name = os.path.splitext(os.path.basename(src))[0]
		print('\n===== [%d/%d] %s (%d bytes) =====' % (i + 1, len(sources), name, len(lyl_text)))
		t0 = time.perf_counter()
		text, info = gen.generate(lyl_text, max_midi_patches=args.max_midi_patches,
			max_measures=args.max_measures, temperature=args.temperature,
			top_k=args.top_k, top_p=args.top_p,
			rep_penalty=args.rep_penalty, rep_window=args.rep_window, verbose=args.verbose)
		dt = time.perf_counter() - t0
		out = os.path.join(args.out_dir, name + '.midiseq2.txt')
		with open(out, 'w', encoding='utf-8') as f:
			f.write(text)
		# sanity: the generated midiseq2 text should parse back into absolute-tick events
		_, events = st.parse_events(text)
		print('[%s] %.1fs | lyl_patches %d | midi_patches %d | measures %d'
			% (info['stop'], dt, info['lyl_patches'], info['midi_patches'], info['measures']))
		print('  parse_events: %d events -> %s' % (len(events), out))


if __name__ == '__main__':
	main()
