
id:     score-topology/{date}-{filename}


data:
  type:                     EventCluster
  root:                     ev-test-paraff.zip
  splits:                   '*1,2/10:3/10'
  batch_size:               1
  args:
    #batch_slice:            2
    with_beading:           True
    stability_base:         10
    position_drift:         0.03
    stem_amplitude:
      mu:                   5.4
      sigma:                2
  args_variant:
    1:
      stability_base:       100


model:
  type:                     BeadPicker
  args:
    n_layers:               2
    d_position:             512
    angle_cycle:            10000
    feature_activation:     tanh
    d_model:                512
    d_inner:                2048
    n_head:                 8
    d_k:                    64
    d_v:                    64
    dropout:                0.1
    scale_emb:              False
    error_weights:
    - 5         # topo
    - 1.e-3     # tick
    - 3         # division
    - 3         # dots
    - 1         # beam
    - 0.1       # stemDirection
    - 3         # grace
    - 3         # warped
    - 3         # full measure
    - 3         # fake
    #                       (loss_topo, loss_tick, loss_division, loss_dots, loss_beam, loss_direction, loss_grace, loss_warped, loss_full, loss_fake)
    loss_weights:           [10, 1.e-6]
    init_gain_n:            4     # 2 * n_layers


trainer:
  env: ~
  device:                   cpu
  save_mode:                best
  epoch:                    2
  moniter:
    field:                  general_error
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       4000
      d_model:              512
