
id:     score_connection/{date}-{filename}

device: cpu
env: ~
  #CUDA_VISIBLE_DEVICES: 0

data:
  file_name:      chopin10-3x100.pkl
  splits:         '*1,2,3,4,5,6,7,8/10:9/10'

model:
  type:           TransformJointer
  args:
    d_word_vec:           512
    d_model:              512
    d_inner:              2048
    n_source_layers:      6
    n_target_layers:      1
    n_head:               8
    d_k:                  64
    d_v:                  64
    dropout:              0.1
    scale_emb:            False

optim:
  lr_mul:             2.
  n_warmup_steps:     4000
