
id:     peris/{date}-{filename}


data:
  type:                     PerisCaption
  root:                     nse-100.zip
  labels:                   labels-20220205.csv
  args: ~



trainer:
  pretrained_model_name_or_path:      CompVis/stable-diffusion-v1-4
