
id:     peris/{date}-{filename}


data:
  type:                     PerisCaption
  root:                     nse-202202.zip
  labels:                   labels-20220205.csv
  args: ~



trainer:
  pretrained_model_name_or_path:      pretrained/models--CompVis--stable-diffusion-v1-4
