
id:     peris/{date}-{filename}


data:
  type:                     PerisCaption
  root:                     nse-202202.zip
  labels:                   labels-20220205.csv
  args:
    alias:                  pretrained/models--CompVis--stable-diffusion-v1-4/tokenizer/alias_vocab.json
    resolution:             512



trainer:
  pretrained_model_name_or_path:      pretrained/models--CompVis--stable-diffusion-v1-4
  num_train_timesteps:                1000
  train_batch_size:                   1
  gradient_accumulation_steps:        4
  max_train_steps:                    3000
  learning_rate:                      5.0e-4
  scale_lr:                           True
  lr_scheduler:                       constant
  lr_warmup_steps:                    0
  num_train_epochs:                   100


optim:
  adam_beta1:                         0.9
  adam_beta2:                         0.9999
  adam_weight_decay:                  1.e-2
  adam_epsilon:                       1.e-8
