
id:     score-topology/{date}-{filename}

env: ~


data:
  type:                     EventCluster
  root:                     ev-test.zip
  splits:                   '*1,2/10:3/10'
  batch_size:               1
  args:
    stability_base:         10
    position_drift:         0.03


model:
  type:           RectifySieveJointer
  args:
    n_trunk_layers:         1
    n_rectifier_layers:     1
    n_source_layers:        1
    n_target_layers:        1
    n_sieve_layers:         1
    d_model:                512
    d_inner:                2048
    n_head:                 8
    d_k:                    64
    d_v:                    64
    angle_cycle:            1000
    dropout:                0.1
    scale_emb:              False
    error_weights:
    - 5         # topo
    - 1.e-3     # tick
    - 3         # division
    - 3         # dots
    - 1         # beam
    - 0.1       # stemDirection
    - 3         # grace
    - 3         # warped
    - 3         # full measure
    - 3         # fake


trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  moniter:
    field:                  general_error
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       4000
      d_model:              512
