
id:     melody/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

model:
  type:                     FrameMatchJointer
  args:
    d_time:                 16
    n_layers_ce:            1
    n_layers_sd:            1
    angle_cycle:            10000
    d_model:                128
    d_inner:                512
    n_head:                 8
    d_k:                    16
    d_v:                    16
    d_time:                 16
    dropout:                0.1
    reg_orthogonality:      0.02
    init_gain_n:            3
    exp_focal:              -8


data:
  type:                     FramePair
  root:                     test.zip
  splits:                   '*1,2/10:9/10'
  batch_size:               16
  args:
    seq_len:                32
    ci_bias_sigma:          1
    ci_center_position:     0.28
    st_scale_sigma:         0.1
    ci_bias_constant:       -1
    random_time0:           0
  #args_variant:


trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  epochs:                   2
  epoch_size:               100
  epoch_duration:           2
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               0.2
      n_warmup_steps:       4000
      d_model:              512


onnx:
  inputs:
  - name: ct
    shape: [1, 32]
    dtype: float32
  - name: cf
    shape: [1, 32, 88]
    dtype: float32
  - name: st
    shape: [1, 32]
    dtype: float32
  - name: sf
    shape: [1, 32, 88]
    dtype: float32
  outputs: [matching, src, tar]
  opset:   14
