
id:     melody/{date}-{filename}


data:
  type:                     FramePair
  root:                     test.zip
  splits:                   '*1,2/10:9/10'
  batch_size:               16
  args:
    c_seq_len:              32
    s_seq_len:              16
    ci_bias_sigma:          4
    ci_center_position:     0.5
    st_scale_sigma:         0.1
    ci_bias_constant:       -1
    random_time0:           0
  #args_variant:
