
id:     text/{date}-{filename}


data:
  type:                     IdTraverser
  splits:                   '*0/1:1/100'
  batch_size:               256
  root:                     ''
  labels:                   ~
  args:
    vocab_size:             49408


model:
  type:                           InvWordEmbed
  args:
    tokenizer_pretrained_path:    pretrained/models--CompVis--stable-diffusion-v1-4
    hidden_size: 768
    vocab_size: 49408


trainer:
  device:         cpu
  save_mode:      all
  epoch:          2
  moniter:
    field:        loss
    mode:         min

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-3
      min_lr:             1.e-6
      decay_rate:         0.98
      n_warmup_steps:     100
