
id:     text/{date}-{filename}


data:
  type:                     IdTraverser
  splits:                   '*0/1:1/100'
  batch_size:               4
  root:                     ''
  labels:                   ~
  args:
    vocab_size:             49408


model:
  type:                           InvWordEmbed
  args:
    tokenizer_pretrained_path:    pretrained/models--CompVis--stable-diffusion-v1-4
