id: lilylet/{date}-{filename}

env: ~

data:
  type: LilyletPatchy
  root: notagenx-from-abc.lilylet-notagen.pt
  splits: '*0..8/10:9/10'
  batch_size: 2
  args_variant: ~
  args:
    patch_size: 16
    patch_length: 2048
    patch_stream: true
    tokenizer_path: assets/lilylet-tokenizer.json
