
id:     melody/{date}-{filename}

env: ~

model:
  type:                     MatchJointer3
  args:
    n_layers_enc:           6
    n_layers_sd:            0
    angle_cycle:            40.e+3
    d_model:                128
    d_inner:                512
    n_head:                 8
    d_k:                    16
    d_v:                    16
    d_time:                 64
    dropout:                0.1
    reg_orthogonality:      0.4
    init_gain_n:            12


data:
  type:                     NotationPair
  root:                     20220616.zip
  splits:                   '*1..8/10:9/8000'
  batch_size:               4
  args:
    seq_len:                16
    ci_bias_sigma:          0
    ci_bias_constant:       0
    ci_center_position:     0
    st_scale_sigma:         0.2
    random_time0:           100.e+3
  #args_variant:


trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  epochs:                   2
  epoch_size:               16
  epoch_duration:           2
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               0.4
      n_warmup_steps:       8000
      d_model:              512


onnx:
  inputs:
  - name: ct
    shape: &tensor_shape [1, 64]
    dtype: float32
  - name: cp
    shape: *tensor_shape
    dtype: int8
  - name: cv
    shape: *tensor_shape
    dtype: int8
  - name: st
    shape: *tensor_shape
    dtype: float32
  - name: sp
    shape: *tensor_shape
    dtype: int8
  - name: sv
    shape: *tensor_shape
    dtype: int8
  outputs: [matching, src, tar]
  opset:   14
