
id:     melody/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

model:
  type:           MatchJointerRaw
  args:
    d_model:      2
    scale_emb:    True

onnx:
  inputs:
    c:     [1, 2, 2]
    s:     [1, 2, 2]
  outputs: [matching, src, tar]
  opset:   12
