
id:     melody/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

model:
  type:           MatchJointer1
  args:
    d_time:       16


data:
  type:                     NotationPair
  root:                     bach-20220607.zip
  splits:                   '*1..8/10:9/10'
  batch_size:               2
  args:
    seq_len:                256
  #args_variant:


trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  moniter:
    field:                  loss
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       4000
      d_model:              512
