
id:     melody/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

model:
  type:           MatchJointer1
  args:
    d_time:       16


data:
  type:                     NotationPair
  root:                     bach-20220608.zip
  splits:                   '*1,2/10:9/10'
  batch_size:               2
  args:
    seq_len:                128
  #args_variant:


trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  epochs:                   2
  epoch_size:               100
  epoch_duration:           30
  moniter:
    field:                  loss
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       4000
      d_model:              512


onnx:
  inputs:
  - name: ct
    shape: [1, 128]
    dtype: float32
  - name: cp
    shape: [1, 128]
    dtype: int8
  - name: cv
    shape: [1, 128]
    dtype: int8
  - name: st
    shape: [1, 128]
    dtype: float32
  - name: sp
    shape: [1, 128]
    dtype: int8
  - name: sv
    shape: [1, 128]
    dtype: int8
  outputs: [matching, src, tar]
  opset:   14
