
id:     melody/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

model:
  type:           MatchJointerRaw
  args:
    d_model:      2
    scale_emb:    True

onnx:
  inputs:
  - name: c
    shape: [1, 2, 2]
    dtype: float32
  - name: s
    shape: [1, 2, 2]
    dtype: float32
  outputs: [matching, src, tar]
  opset:   12
