
id:     paraff/{date}-{filename}


data:
  type:                     MidiseqEmbed
  root:                     writer-20231004
  splits:                   '*1..3/5:4/5'
  batch_size:               2
  args:
    # neighbor measure blending
    blend_p:                0.6
    blend_length_sigma:     0.2


model:
  type:                     SeqShareSE
  args:
    n_vocab:                324
    d_latent:               256
    n_seq_max:              512
    d_model:                256
    d_inner:                1024
    n_layers:               4
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    decode_weight:          0.06
    mask_dropout:           0


trainer:
  env: ~
  device:                   cuda
  save_mode:                best
  epoch:                    2
  epoch_size:               64
  report_step_unit:         examples
  moniter:
    field:                  loss
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               10
      n_warmup_steps:       6400
      d_model:              256
