
id:     paraff/{date}-{filename}


data:
  type:                     SentenceShift
  root:                     20230301.paraff
  splits:                   '*0/1:0/100'
  batch_size:               2
  args:
    n_seq:                  512


model:
  type:                     TokenGen
  args:
    n_vocab:                81
    n_seq_max:              512
    d_model:                128
    d_inner:                512
    n_layers:               8
    n_head:                 8
    d_k:                    16
    d_v:                    16
    dropout:                0.1
    emb_prj_weight_sharing: True
    scale_emb_or_prj:       prj


onnx:
  inputs:
  - name:   in_seq
    dtype:  int8
    shape:  [1, 512]
  opset: 14
  outputs:
  - out_seq
