
id:     paraff/{date}-{filename}


data:
  type:                         VisionLanguage
  root:                         ly-vl20250226
  splits:                       '*0/1'
  batch_size:                   2
  args:
    prompt_template:            paraffUndPrompt.jinja
    tokenizer:
      path:                     deepseek-ai/Janus-Pro-7B
