
id:     paraff/{date}-{filename}


data:
  type:                     PhasedParagraph
  root:                     20230804-paragraph.yaml
  splits:                   '*1..8/10:9/10'
  batch_size:               2
  args:
    n_seq_word:             512
    seq_tail_padding:       16
    n_seq_phase:            384 # cannot less than the length of the longest paragraph
    descriptor_drop:        0.3
    descriptor_drop_sigma:  1.
    with_summary:           False
    with_graph:             True
    graph_augmentor:
      drop_p:               0.02
      x_factor_sigma:       0.04
      drift_sigma:          0.02
      confidence_sigma:     0.2
  args_variant:
    1:
      graph_augmentor:
        drop_p:             0


model:
  type:                     GraphParaffTranslator
  args:
    d_model:                256
    with_pos:               True
    encoder_config:
      unidirectional:       False
      n_semantic:           80
      n_staff:              3
      d_position:           128
      angle_cycle:          1000
      n_layers:             4
      d_inner:              1024
      n_head:               8
      d_k:                  32
      d_v:                  32
      dropout:              0.1
    decoder_config:
      n_trg_vocab:          102
      angle_cycle:          10000
      d_inner:              1024
      n_layers:             6
      n_head:               8
      d_k:                  32
      d_v:                  32
      dropout:              0.1
      scale_emb:            True


trainer:
  env: ~
  device:                   cuda
  save_mode:                best
  epoch:                    100
  report_step_unit:         examples
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       6400
      d_model:              256


onnx:
  multiple:
    seq32:
      model_postfix: Onnx
      inputs:
      - name:   ids
        dtype:  uint8
        shape:  &sz1_32 [1, 32]
      - name:   staff
        dtype:  uint8
        shape:  *sz1_32
      - name:   confidence
        dtype:  float32
        shape:  *sz1_32
      - name:   x
        dtype:  float32
        shape:  *sz1_32
      - name:   y
        dtype:  float32
        shape:  *sz1_32
      - name:   sy1
        dtype:  float32
        shape:  *sz1_32
      - name:   sy2
        dtype:  float32
        shape:  *sz1_32
      - name:   premier
        dtype:  uint8
        shape:  &sz512 [1, 512]
      - name:   position
        dtype:  float32
        shape:  *sz512
      opset: 14
      outputs:
      - logits
    seq128:
      model_postfix: Onnx
      inputs:
      - name: ids
        dtype: uint8
        shape: &sz1_128 [1, 128]
      - name: staff
        dtype: uint8
        shape: *sz1_128
      - name: confidence
        dtype: float32
        shape: *sz1_128
      - name: x
        dtype: float32
        shape: *sz1_128
      - name: y
        dtype: float32
        shape: *sz1_128
      - name: sy1
        dtype: float32
        shape: *sz1_128
      - name: sy2
        dtype: float32
        shape: *sz1_128
      - name: premier
        dtype: uint8
        shape: *sz512
      - name:   position
        dtype:  float32
        shape:  *sz512
      opset: 14
      outputs:
      - logits
    seq512:
      model_postfix: Onnx
      inputs:
      - name: ids
        dtype: uint8
        shape: &sz1_512 [1, 512]
      - name: staff
        dtype: uint8
        shape: *sz1_512
      - name: confidence
        dtype: float32
        shape: *sz1_512
      - name: x
        dtype: float32
        shape: *sz1_512
      - name: y
        dtype: float32
        shape: *sz1_512
      - name: sy1
        dtype: float32
        shape: *sz1_512
      - name: sy2
        dtype: float32
        shape: *sz1_512
      - name: premier
        dtype: uint8
        shape: *sz512
      - name:   position
        dtype:  float32
        shape:  *sz512
      opset: 14
      outputs:
      - logits
