
id:     paraff/{date}-{filename}


data:
  type:                     PhasedParagraph
  root:                     20230804-paragraph.yaml
  splits:                   '*1..8/10:9/10'
  batch_size:               2
  args:
    n_seq_word:             512
    n_seq_phase:            256
    descriptor_drop:        0.3
    descriptor_drop_sigma:  1.
    with_summary:           True
    with_graph:             True
    graph_augmentor:
      drop_p:               0.02
      x_factor_sigma:       0.04
      drift_sigma:          0.02
      confidence_sigma:     0.2


model:
  type:                     GraphParaffEncoder
  args:
    d_model:                256
    n_semantic:             80
    n_staff:                3
    d_position:             128
    angle_cycle:            1000
    n_layers:               4
    d_inner:                1024
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    word_decoder_config:
      n_vocab:              102
      pad_id:               0
      summary_id:           1
      finale_id:            5
      n_seq_max:            512
      d_model:              256
      d_inner:              1024
      n_layers:             6
      n_head:               8
      d_k:                  32
      d_v:                  32
      dropout:              0.1
      kld_weight:           1.e-6
      mask_dropout:         0
    word_decoder_pretrain:
      weight:               training/paraff/20230627-paraff-vae-shared-0613-d256-l4-kld1e-6/model_236_loss_3.732e-02.chkpt
      defreeze_layers:      4
      init_layers:          2


trainer:
  env: ~
  device:                   cuda
  save_mode:                best
  epoch:                    100
  report_step_unit:         examples
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       6400
      d_model:              256
