
id:     paraff/{date}-{filename}


data:
  type:                     PhasedParagraph
  root:                     20230630-paragraph.yaml
  splits:                   '*1..8/10:9/10'
  batch_size:               2
  args:
    n_seq_word:             512
    seq_tail_padding:       16
    n_seq_phase:            256
    descriptor_drop:        0.3
    descriptor_drop_sigma:  1.
    with_summary:           True
    encoder:
      weight:               ./training/paraff/20230627-paraff-vae-shared-0613-d256-l4-kld1e-6/model_236_loss_3.732e-02.pt
      device:               cpu
      batch_size:           16
      test:                 True


model:
  type:                     PhaseGen
  args:
    d_model:                256
    n_vocab:                14
    pad_id:                 0
    summary_id:             1
    n_layers:               4
    d_inner:                1024
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    angle_cycle:            10000
    random_base:            False
    latent_l2_reg:          0
    mask_score_primer:      False
    lora_decoder_config:
      n_lora_layers:        8
      d_latent:             256
      lora_config:
        r:                  4
        alpha:              1
        bias:               False
      n_vocab:              102
      pad_id:               0
      d_model:              256
      d_inner:              1024
      n_layers:             8
      n_head:               8
      d_k:                  32
      d_v:                  32
      dropout:              0.1
      angle_cycle:          10000
    lora_decoder_pretrain:
      weight:               training/paraff/20230707-paraff-score-decoder-test/untraied.chkpt


trainer:
  env: ~
  device:                   cuda
  save_mode:                best
  epoch:                    100
  report_step_unit:         examples
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       6400
      d_model:              256


onnx:
  multiple:
    phaseGen128:
      opset: 14
      inputs:
      - name:     ids
        dtype:    uint8
        shape:    &sz128 [1, 128]
      - name:     f_pos
        dtype:    int16
        shape:    *sz128
      - name:     b_pos
        dtype:    int16
        shape:    *sz128
      - name:     summary
        dtype:    float32
        shape:    [1, 128, 256]
      - name:     mask
        dtype:    bool
        shape:    *sz128
      - name:     next
        dtype:    bool
        shape:    *sz128
      outputs:
      - latent
    decoder128:
      model_postfix: DecoderLora
      state_field: extra
      opset: 14
      inputs:
      - name: input_ids
        dtype: uint8
        shape: *sz128
      - name: position
        dtype: int16
        shape: *sz128
      - name: latent
        dtype: float32
        shape: [1, 256]
      outputs:
      - logits
