
id:     paraff/{date}-{filename}


data:
  type:                     SentenceShift
  root:                     20230301.paraff
  splits:                   '*0/1'
  batch_size:               2
  args:
    n_seq:                  512
