
id:               paraff/{date}-{filename}

data:
  type:                       ScoreMeasurewise
  root:                       20231026-test/20231027-paragraph.yaml
  splits:                     '*1..8/10:9/10'
  batch_size:                 2
  args:
    n_seq_word:               512
    n_seq_midi:               64
    seq_tail_padding:         16
    descriptor_drop:          0.3
    descriptor_drop_sigma:    1.
    strength_sigma:           0.1
    strength_pow_sigma:       0.6
    key_shift_sigma:          5


model:
  type:                     MidiParaffTranslator
  args:
    d_model:                256
    d_inner:                1024
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    encoder_config:
      n_layer:              4
      n_type:               4
      n_pitch:              91
      pos_encoder:          sinusoid
      angle_cycle:          100000
    decoder_config:
      n_layers:             6
      n_trg_vocab:          127
      angle_cycle:          10000
      scale_emb:            True
      pos_encoder:          sinusoid
    n_midi_dec_layer:       2
    d_midi_dec:             1
    midi_weight:            1


trainer:
  env: ~
  device:                   cuda
  save_mode:                best
  epoch:                    100
  report_step_unit:         examples
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       6400
      d_model:              256


_vocab: &vocab [PAD,MSUM,BOS,EOS,BOM,EOM,VB,S1,S2,S3,Cg,Cf,Cc,K0,K1,K2,K3,K4,K5,K6,K_1,K_2,K_3,K_4,K_5,K_6,TN1,TN2,TN3,TN4,TN5,TN6,TN7,TN8,TN9,TN10,TN11,TN12,TD2,TD4,TD8,TD16,a,b,c,d,e,f,g,As,Af,Ass,Aff,Osup,Osub,O0,Ova,Ovb,D1,D2,D4,D8,D16,D32,D64,D128,D256,Dot,Bl,Br,Mu,Md,Rest,RSpace,W2,W3,W4,W5,W6,W7,W8,W9,W10,W12,W16,W24,W32,Wx,W,G,TM8,TM16,TM32,TM64,TM128,TM256,TC8,TC16,TC32,TC64,TC128,TC256,EslurL,EslurR,Etie,Earp,Etr,Efer,Esf,Est,Estm,Eac,Emor,Epr,Eturn,Epor,Eten,Emar,Ecre,Edim,Ecds,EDf,EDp,EDm,EDr,EDs,EDz]
