
id:     paraff/{date}-{filename}


data:
  type:                     SentenceShift
  root:                     20230612.paraff
  splits:                   '*1..98/100:99/100'
  batch_size:               2
  args:
    n_seq:                  360
    descriptor_drop:        0.3
    descriptor_drop_sigma:  0.5
  args_variant:
    1:
      descriptor_drop:      0


model:
  type:                     SparseAE
  args:
    n_vocab:                137
    d_latent:               0xfff8
    pad_id:                 0
    summary_id:             1
    finale_id:              5
    n_seq_max:              512
    d_model:                256
    d_inner:                1024
    n_layers:               8
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    freeze_factor:          1
    freeze_step:            1.e-4
    mask_dropout:           0.3


trainer:
  device:                   cuda
  save_mode:                best
  epoch:                    100
  moniter:
    field:                  loss
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       3200
      d_model:              256
