
id:               paraff/{date}-{filename}

data:
  type:                       ScoreMeasurewise
  root:                       20231026-test/20231027-paragraph.yaml
  splits:                     '*1..8/10:9/10'
  batch_size:                 2
  args:
    n_seq_word:               512
    n_seq_midi:               64
    seq_tail_padding:         16
    descriptor_drop:          0.3
    descriptor_drop_sigma:    1.
    strength_sigma:           0.1
    strength_pow_sigma:       0.6
    key_shift_sigma:          5


model:
  type:                     MidiParaffTranslator
  args:
    d_model:                256
    d_inner:                1024
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    encoder_config:
      n_layer:              4
      n_type:               4
      n_pitch:              91
      pos_encoder:          sinusoid
      angle_cycle:          100000
    decoder_config:
      n_layers:             6
      n_trg_vocab:          127
      angle_cycle:          10000
      scale_emb:            True
      pos_encoder:          sinusoid
    n_midi_dec_layer:       2
    d_midi_dec:             1
    midi_weight:            1
