
id:     paraff/{date}-{filename}


data:
  type:                     PhasedParagraph
  root:                     20230630-paragraph.yaml
  splits:                   '*1..8/10:9/10'
  batch_size:               2
  args:
    n_seq_word:             512
    seq_tail_padding:       16
    n_seq_phase:            256
    descriptor_drop:        0.3
    descriptor_drop_sigma:  1.
    with_summary:           False
    encoder:
      weight:               ./training/paraff/20230627-paraff-vae-shared-0613-d256-l4-kld1e-6/model_236_loss_3.732e-02.pt
      device:               cpu
      batch_size:           16
      test:                 True


model:
  type:                     PhasePre
  args:
    d_model:                256
    n_type:                 14
    n_vocab:                102
    d_phase:                128
    d_token:                128
    d_summary:              256
    n_layers:               4
    d_inner:                1024
    n_head:                 8
    d_k:                    32
    d_v:                    32
    dropout:                0.1
    angle_cycle:            10000


trainer:
  env: ~
  device:                   cuda
  save_mode:                best
  epoch:                    100
  report_step_unit:         examples
  moniter:
    field:                  acc
    mode:                   max

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               1
      n_warmup_steps:       6400
      d_model:              256


onnx:
  opset: 14
  inputs:
  - name:     phid
    dtype:    uint8
    shape:    &sz192 [1, 192]
  - name:     f_pos
    dtype:    int16
    shape:    *sz192
  - name:     b_pos
    dtype:    int16
    shape:    *sz192
  - name:     summary
    dtype:    float32
    shape:    [1, 192, 256]
  - name:     ph_mask
    dtype:    bool
    shape:    *sz192
  - name:     next
    dtype:    bool
    shape:    *sz192
  - name:     id
    dtype:    uint8
    shape:    &sz448 [1, 448]
  - name:     id_pos
    dtype:    int16
    shape:    *sz448
  outputs:
  - logits
