
id:     peris/{date}-{filename}


model:
  type:                     ClipVisionBinary
  args:
    channels:               7
    clip_config:
      add_cross_attention:              false
      architectures: ~
      attention_dropout:                0.
      bad_words_ids: ~
      bos_token_id: ~
      chunk_size_feed_forward:          0
      cross_attention_hidden_size: ~
      decoder_start_token_id: ~
      diversity_penalty:                0.
      do_sample: false
      dropout:                          0.
      early_stopping:                   False
      encoder_no_repeat_ngram_size:     0
      eos_token_id: ~
      finetuning_task: ~
      forced_bos_token_id: ~
      forced_eos_token_id: ~
      hidden_act:                       quick_gelu
      hidden_size:                      768
      id2label:
        0: LABEL_0
        1: LABEL_1
      label2id:
        LABEL_0: 0
        LABEL_1: 1
      image_size:                       224
      initializer_factor:               1.
      initializer_range:                0.02
      intermediate_size:                3072
      is_decoder:                       False
      is_encoder_decoder:               False
      layer_norm_eps:                   1.e-05
      length_penalty:                   1.
      max_length:                       20
      min_length:                       0
      model_type:                       clip_vision_model
      no_repeat_ngram_size:             0
      num_attention_heads:              12
      num_beam_groups:                  1
      num_beams:                        1
      num_hidden_layers:                12
      num_return_sequences:             1
      output_attentions:                False
      output_hidden_states:             False
      output_scores:                    False
      pad_token_id: ~
      patch_size:                       32
      prefix: ~
      projection_dim:                   512
      problem_type: ~
      pruned_heads: {}
      remove_invalid_values:            False
      repetition_penalty:               1.
      return_dict:                      True
      return_dict_in_generate:          False
      sep_token_id: ~
      task_specific_params: ~
      temperature:                      1.
      tie_encoder_decoder:              False
      tie_word_embeddings:              True
      tokenizer_class: ~
      top_k:                            50
      top_p:                            1.
      torch_dtype: ~
      torchscript:                      False
      transformers_version:             4.16.0.dev0
      use_bfloat16:                     False


data:
  type:                     BalanceLabeledPeris
  root:                     nse-202202.zip
  labels:                   labels-20220921.csv
  splits:                   '*1..8/10:9/10'
  batch_size:               1
  args:
    label_fields:           ['score_binary']
    epoch_n:                20
    score_binary:
      thresholds:           [3, 4, 5, 6, 7, 8, 9]
    groups:
    - (_1.score >  0) & (_1.score < 3)
    - (_1.score >= 3) & (_1.score < 4)
    - (_1.score >= 4) & (_1.score < 5)
    - (_1.score >= 5) & (_1.score < 6)
    - (_1.score >= 6) & (_1.score < 7)
    - (_1.score >= 7) & (_1.score < 8)
    - (_1.score >= 8) & (_1.score < 9)
    - (_1.score >= 9)
    augmentor:
      size_fixed:
        size:               224
        padding_mode:       constant
      affine:
        degrees:            5
        interpolation:      'BILINEAR'
  args_variant:
    1:
      epoch_n:              10


trainer:
  device:         cpu
  save_mode:      best
  epoch:          2
  moniter:
    field:        error
    mode:         min

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-3
      min_lr:             1.e-6
      decay_rate:         0.98
      n_warmup_steps:     10000
