
id:     score-vision/{date}-{filename}

model:
  type:                     ScoreSemanticValue
  args:
    d_model:                512
    d_inner:                2048
    n_head:                 8
    d_k:                    64
    d_v:                    64
    angle_cycle:            1000
    n_layers:               1
    dropout:                0.1
    scale_emb:              False
    n_semantic:             78

data:
  type:                     ScoreFault
  root:                     fault-test.zip
  splits:                   '*1,2/10:0/10'
  batch_size:               1
  args:
    n_seq_max:              64
    confidence_temperature: 1
    position_drift:         0.06

trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  moniter:
    field:                  bce
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               0.4
      n_warmup_steps:       4000
      d_model:              512
