
id:     score-vision/{date}-{filename}

model:
  type:                     ScoreResidueU
  args:
    in_channels:            1
    out_channels:           3
    residue_blocks:         0
    base_depth:             4
    base_init_width:        64
    channel_weights:        [1, 4, 2]
    freeze_base:            False
    compounder:
      list:
        - label:              box_Staff
          channels:           [1]
        - label:              box_System
          channels:           [0, 1]

data:
  type:           ScorePage
  root:           testPage/
  splits:         '*1..8/10:0/10'
  batch_size:     1
  args:
    trans:                    [HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    augmentor:
      skip_p:                 0.1
      aa_scale:               2
      tinter:
        fore_pow:             9.
        fore_sigma:           0.2
        fore_scale_range:     [12, 100]
        fore_blur_range:      [0, 1]
        back_pow:             6.
        back_sigma:           0.3
        back_scale_range:     [0.1, 1.2]
        back_blur_range:      [0, 3]
      gaussian_noise:
        sigma:                0.03
      affine:
        padding_scale:        1.06
        angle_sigma:          1.
        scale_sigma:          0.3
        scale_mu:             1
        #scale_limit:          1.
        size_limit:           1200
        std_size:             720
      crease:
        intensity:            4
        margin:               0.02
        width:                0.03
        flip_p:               0.7
      gaussian_blur:
        sigma:                1.2
      flip_mark:
        intensity_range:      [0, 0.1]
      distortion:   
        scale:                2
        scale_sigma:          0.4
        intensity:            0.8
        intensity_sigma:      0.3
        squeeze_sigma:        0.2
        noise_weights_sigma:  1
        noise:                temp/perlin-4.npy
  args_variant:
    1:
      augmentor:
        skip_p:               0.3
        distortion:
          intensity:          0.2
        flip_mark:
          intensity_range:    [0, 0.06]
        tinter:
          back_sigma:         0.1
          fore_sigma:         0.06
      gaussian_noise:
        sigma:                0.01

trainer:
  device:         cpu
  save_mode:      best
  epoch:          2
  moniter:
    field:        acc
    mode:         max

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             2.e-4
      min_lr:             1.e-7
      decay_rate:         0.998
      n_warmup_steps:     80000
