
id:     score-vision/{date}-{filename}

model:
  type:                     ScoreRegression
  args:
    in_channels:            1
    out_channels:           2
    width_mask:             False
    loss_gradient0:         0
    backbone:
      type:                 unet
      unet_depth:           6
      unet_init_width:      32

data:
  trans:                    [HWC2CHW, Tar_HWC2CHW, Tar_GradientY]
  slicing_width:            512
