
id:     score-vision/{date}-{filename}

data:
  type:           RenderScore
  root:           test10/
  splits:         '*1..8/10:9/10'
  batch_size:     1
  args:
    labels:       &labels     [
                                ClefG, ClefF, ClefC,
                                NoteheadS0, NoteheadS1, NoteheadS2,
                                Rest0, Rest1, Rest2, RestFlag,
                                Dot, Flag3,
                                AccNatural, AccSharp, AccFlat, AccDoublesharp, AccFlatflat,
                                Timesig,
                                OctaveShift8, OctaveShift0,
                                Fingering,
                                Dynamic,
                                Script,
                                VoltaLeft, VoltaRight,
                                vline_BarMeasure, vline_Stem, vline_BarTerminal, vline_BarSegment,
                                SlurBegin, SlurEnd, Wedge,
                                TremoloLeft, TremoloRight, TremoloMiddle,
                                KeyAcc, TempoNotehead, GraceNotehead, BeamLeft, BeamRight, BeamContinue, SignLined, SignInterval, StemTip, StemHead,
                              ]
    trans:                    [Mono, HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    slicing_width:            512
    unit_size:                8
    input_mask:               False
    cache_labels:             True
    crop_margin:              136
    augmentor:
      tinter:
        fore_pow:             4.
        fore_sigma:           0.6
        fore_scale_range:     [40, 100]
        fore_blur_range:      [0, 1]
        back_pow:             3.
        back_sigma:           0.4
        back_scale_range:     [0.1, 0.5]
        back_blur_range:      [0, 8]
      gaussian_noise:
        sigma:                0.02
      gaussian_blur:
        sigma:                0.4
      distortion:
        noise:                temp/perlin-12.npy
        scale:                1.4
        scale_sigma:          0.2
        intensity:            0.03
        intensity_sigma:      0.4
        squeeze_sigma:        0
        target_border:        BORDER_REPLICATE

model:
  type:                     ScoreWidgets
  args:
    in_channels:            1
    out_channels:           84
    freeze_mask:            False
    unit_size:              8
    labels:                 *labels
    mask:
      type:                 unet
      unet_depth:           5
      unet_init_width:      32
    backbone:
      type:                 unet
      unet_depth:           4
      unet_init_width:      64
    channel_weights_rate:   1.e-5
    clip_margin:            12
    metric_quota:           2000
    wide_mask:              True
    channel_factor:
      ClefG:                2
      ClefF:                2
      ClefC:                1
      Timesig:              2
      NoteheadS0:           2
      NoteheadS1:           2.4
      NoteheadS2:           2.8
      Dot:                  2
      vline_BarMeasure:     2
      vline_Stem:           2
      Flag3:                4

      AccNatural:           1.6
      AccSharp:             1.6
      AccFlat:              1.6
      KeyAcc:               1.6
      Rest0:                2
      Rest1:                2
      Rest2:                1.6
      RestFlag:             1.4
      OctaveShift8:         1.6
      OctaveShift0:         1.6
      OctaveShift15:        1

      AccDoublesharp:       1
      AccFlatflat:          1
      SlurBegin:            1
      SlurEnd:              1
      VoltaLeft:            1.2
      VoltaRight:           1.2
      vline_BarTerminal:    1
      vline_BarSegment:     1
      TempoNotehead:        1.6
      GraceNotehead:        1.6
      SignLined:            1.6
      SignInterval:         1.6
      BeamLeft:             1
      BeamRight:            1
      BeamContinue:         1
      TremoloLeft:          1
      TremoloRight:         1
      TremoloMiddle:        1
      StemTip:              1
      StemHead:             1

      Fingering:            0.6
      Dynamic:              0.6
      Script:               0.6
      rect_Text:            0.2
      rect_Lyric:           0.2
      Wedge:                0.6


trainer:
  device:         cuda
  save_mode:      best
  epoch:          5
  epochs:         5
  epoch_size:     12000
  epoch_duration: 3600
  val_batch_size: 4
  moniter:
    field:        contour
    mode:         max

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-3
      min_lr:             1.e-9
      decay_rate:         0.98
      n_warmup_steps:     10000
