
id:     score-vison/{date}-{filename}

model:
  type:                     ScoreResidue
  args:
    in_channels:            1
    out_channels:           3
    residue_blocks:         0
    base_depth:             4
    base_stack_filters:     [16, 32, 48]
    freeze_base:            False

data:
  trans:                    [HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
  compound_labels:
    list:
      - label:              box_Staff
        channels:           [1]
      - label:              box_System
        channels:           [0, 1]
