
id:     score-vision/{date}-{filename}

model:
  type:                     ScoreWidgetsMask
  args:
    in_channels:            1
    mask:
      type:                 unet
      unet_depth:           5
      unet_init_width:      32
    backbone:
      type:                 non-specific

data:
  type:           ScoreMask
  root:           test7/
  splits:         '*1,2,3,4,5,6,7,8/10:9/10'
  batch_size:     1
  args:
    trans:                    [Mono, HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    slicing_width:            512
    crop_margin:              136
    augmentor:
      tinter:
        fore_pow:             6.
        fore_sigma:           0.6
        fore_scale_range:     [40, 100]
        fore_blur_range:      [0, 1]
        back_pow:             6.
        back_sigma:           0.4
        back_scale_range:     [0.1, 0.5]
        back_blur_range:      [0, 8]
      gaussian_noise:
        sigma:                0.02
      gaussian_blur:
        sigma:                1.5
      distortion:
        noise:                temp/perlin-12.npy
        scale:                1.4
        scale_sigma:          0.2
        intensity:            0.06
        intensity_sigma:      0.4

trainer:
  device:         cpu
  save_mode:      best
  epoch:          2

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-4
      min_lr:             1.e-6
      decay_rate:         0.92
      n_warmup_steps:     200
