
id:     score-vision/{date}-{filename}

data:
  type:           RenderScore
  root:           test7/
  splits:         '*1,2,3,4,5,6,7,8/10:9/10'
  batch_size:     1
  args:
    labels:                   [
                                ClefG, ClefF, TimesigFour, TimesigThree, TimesigTwo, NoteheadS0, NoteheadS1, NoteheadS2, Dot, vline_BarMeasure, vline_Stem, Flag3,
                                TimesigC44, TimesigC22, TimesigEight, TimesigSix, AccNatural, AccSharp, AccFlat, KeyAcc, Rest0, Rest1, Rest2, Rest3, Rest4, OctaveShift8, OctaveShift0,
                                AccDoublesharp, AccFlatflat, TimesigOne, TimesigNine, Rest5, Rest6, SlurBegin, SlurEnd, VoltaLeft, VoltaRight, vline_BarTerminal, vline_BarSegment, TempoNotehead, GraceNotehead,
                                f, p, m, ScriptFermata, ScriptSforzato, ScriptStaccato, ScriptStaccatissimo, ScriptTurn, ScriptTrill, ScriptSegno, ScriptCoda, ScriptArpeggio, ScriptPrall, ScriptMordent, ScriptTenuto, PedalStar, PedalPed, TimesigFive, TimesigSeven, TimesigZero, One, Two, Three, Four, Five, rect_Text, rect_Lyric, BeamLeft, BeamRight, BeamContinue, CrescendoBegin, CrescendoEnd, DecrescendoBegin, DecrescendoEnd,
                              ]
    trans:                    [Mono, HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    slicing_width:            512
    unit_size:                8
    input_mask:               False
    cache_labels:             True
    crop_margin:              136
    augmentor:
      tinter:
        fore_pow:             4.
        fore_sigma:           0.2
        fore_scale_range:     [40, 100]
        fore_blur_range:      [0, 1]
        back_pow:             3.
        back_sigma:           0.2
        back_scale_range:     [0.1, 0.5]
        back_blur_range:      [0, 8]
      gaussian_noise:
        sigma:                0.01
      gaussian_blur:
        sigma:                0.6
      distortion:
        noise:                temp/perlin-12.npy
        scale:                1.4
        scale_sigma:          0.2
        intensity:            0.03
        intensity_sigma:      0.4
