
id:     score-vison/{date}-{filename}

model:
  type:                     ScoreWidgetsMask
  args:
    in_channels:            1
    mask:
      type:                 unet
      unet_depth:           5
      unet_init_width:      32
    backbone:
      type:                 non-specific

data:
  trans:                    [Mono, HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
  slicing_width:            512
