
id:     score-vision/{date}-{filename}

data:
  type:           RenderScore
  root:           working/test/
  splits:         '*1..8/10:9/10'
  batch_size:     1
  args:
    labels:       &labels     [
                                ClefG, ClefF, ClefC,
                                NoteheadS0, NoteheadS1, NoteheadS2,
                                Rest0, Rest1, Rest2, Rest3, Rest4, Rest5, Rest6,
                                Dot, Flag3,
                                AccNatural, AccSharp, AccFlat, AccDoublesharp, AccFlatflat,
                                TimesigC44, TimesigC22, TimesigZero, TimesigOne, TimesigTwo, TimesigThree, TimesigFour, TimesigFive, TimesigSix, TimesigSeven, TimesigEight, TimesigNine,
                                OctaveShift8, OctaveShift0,
                                One, Two, Three, Four, Five,
                                f, p, m, s, z,
                                ScriptFermata, ScriptSforzato, ScriptStaccato, ScriptStaccatissimo, ScriptTurn, ScriptTrill, ScriptSegno, ScriptCoda, ScriptArpeggio, ScriptPrall, ScriptMordent, ScriptTenuto, PedalStar, PedalPed,
                                VoltaLeft, VoltaRight,
                                vline_BarMeasure, vline_Stem, vline_BarTerminal, vline_BarSegment,
                                rect_Lyric,
                                SlurBegin, SlurEnd, CrescendoBegin, CrescendoEnd, DecrescendoBegin, DecrescendoEnd,
                                TremoloLeft, TremoloRight, TremoloMiddle,
                                KeyAcc, TempoNotehead, GraceNotehead, BeamLeft, BeamRight, BeamContinue, SignLined, SignInterval, StemTip, StemHead,
                              ]
    trans:                    [Mono, HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    slicing_width:            512
    unit_size:                8
    input_mask:               False
    cache_labels:             True
    crop_margin:              136
    augmentor:
      tinter:
        fore_pow:             4.
        fore_sigma:           0.6
        fore_scale_range:     [40, 100]
        fore_blur_range:      [0, 1]
        back_pow:             3.
        back_sigma:           0.4
        back_scale_range:     [0.1, 0.5]
        back_blur_range:      [0, 8]
      gaussian_noise:
        sigma:                0.02
      gaussian_blur:
        sigma:                0.4
      distortion:
        noise:                temp/perlin-12.npy
        scale:                1.4
        scale_sigma:          0.2
        intensity:            0.03
        intensity_sigma:      0.4
        squeeze_sigma:        0
        target_border:        BORDER_REPLICATE

model:
  type:                     ScoreWidgets
  args:
    in_channels:            1
    out_channels:           84
    freeze_mask:            False
    unit_size:              8
    labels:                 *labels
    mask:
      type:                 unet
      unet_depth:           5
      unet_init_width:      32
    backbone:
      type:                 unet
      unet_depth:           4
      unet_init_width:      64
    channel_weights_rate:   1.e-5
    clip_margin:            12
    metric_quota:           2000
    wide_mask:              True
    channel_factor:
      ClefG:                2
      ClefF:                2
      TimesigFour:          2
      TimesigThree:         2
      TimesigTwo:           2
      NoteheadS0:           2
      NoteheadS1:           2
      NoteheadS2:           2
      Dot:                  2
      vline_BarMeasure:     2
      vline_Stem:           2
      Flag3:                4

      TimesigC44:           1.2
      TimesigC22:           1.2
      TimesigEight:         1.2
      TimesigSix:           1.2
      AccNatural:           1.6
      AccSharp:             1.6
      AccFlat:              1.6
      KeyAcc:               1.6
      Rest0:                2
      Rest1:                2
      Rest2:                1.6
      Rest3:                1.6
      Rest4:                1.6
      OctaveShift8:         1.6
      OctaveShift0:         1.6
      OctaveShift15:        1

      AccDoublesharp:       1
      AccFlatflat:          1
      TimesigOne:           1
      TimesigNine:          1
      Rest5:                1
      Rest6:                1
      SlurBegin:            1
      SlurEnd:              1
      VoltaLeft:            1
      VoltaRight:           1
      vline_BarTerminal:    1
      vline_BarSegment:     1
      TempoNotehead:        1
      GraceNotehead:        1
      SignLined:            1
      SignInterval:         1
      BeamLeft:             1
      BeamRight:            1
      BeamContinue:         1
      TremoloLeft:          1
      TremoloRight:         1
      TremoloMiddle:        1
      StemTip:              1
      StemHead:             1
      Zero:                 1
      Six:                  1
      Seven:                1
      Eight:                1
      Nine:                 1
      ClefC:                1

      f:                    0.6
      p:                    0.6
      m:                    0.6
      s:                    0.6
      r:                    0.6
      z:                    0.6
      ScriptFermata:        0.6
      ScriptSforzato:       0.6
      ScriptStaccato:       0.6
      ScriptStaccatissimo:  0.6
      ScriptTurn:           0.6
      ScriptTrill:          0.6
      ScriptSegno:          1
      ScriptCoda:           1
      ScriptArpeggio:       0.6
      ScriptPrall:          0.6
      ScriptMordent:        0.6
      ScriptTenuto:         0.6
      ScriptShortFermata:   0.6
      ScriptMarcato:        0.6
      ScriptPortato:        0.6
      PedalStar:            0.6
      PedalPed:             0.6
      TimesigFive:          1
      TimesigSeven:         1
      TimesigZero:          1
      One:                  1
      Two:                  1
      Three:                1
      Four:                 1
      Five:                 1
      rect_Text:            0.2
      rect_Lyric:           0.2
      CrescendoBegin:       0.8
      CrescendoEnd:         0.8
      DecrescendoBegin:     0.8
      DecrescendoEnd:       0.8


trainer:
  device:         cuda
  save_mode:      best
  epoch:          5
  epochs:         5
  epoch_size:     12000
  epoch_duration: 3600
  val_batch_size: 4
  moniter:
    field:        contour
    mode:         max

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-3
      min_lr:             1.e-9
      decay_rate:         0.98
      n_warmup_steps:     10000
