
id:     score-vision/{date}-{filename}

model:
  type:                     ScoreResidueU
  args:
    in_channels:            1
    out_channels:           3
    residue_blocks:         0
    base_depth:             4
    base_init_width:        64
    freeze_base:            False
    compounder:
      list:
        - label:              box_Staff
          channels:           [1]
        - label:              box_System
          channels:           [0, 1]

data:
  type:           ScorePage
  root:           testPage/
  splits:         '*1,2,3,4,5,6,7,8/10:0/10'
  batch_size:     1
  args:
    trans:                    [HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    augmentor:
      tinter:
        fore_pow:             6.
        fore_sigma:           0.6
        fore_scale_range:     [40, 100]
        fore_blur_range:      [0, 1]
        back_pow:             8.
        back_sigma:           0.24
        back_scale_range:     [0.1, 1.6]
        back_blur_range:      [0, 8]
      gaussian_noise:
        sigma:                0.03
      affine:
        padding_scale:        1.06
        angle_sigma:          1.
        scale_sigma:          0.2
        scale_mu:             0.6
        scale_limit:          1.
        size_limit:           400
      crease:
        intensity:            4
        margin:               0.02
        width:                0.03
      gaussian_blur:
        sigma:                1.5
      flip_mark:
        intensity_range:      [0, 0.1]
      distortion:   
        scale:                2
        scale_sigma:          0.4
        intensity:            1.6
        intensity_sigma:      0.6

trainer:
  device:         cpu
  save_mode:      best
  epoch:          2
  moniter:
    field:        acc
    mode:         max

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-4
      min_lr:             1.e-6
      decay_rate:         0.92
      n_warmup_steps:     200
