
id:     score-vision/{date}-{filename}

model:
  type:                     ScoreResidue
  args:
    in_channels:            1
    out_channels:           3
    residue_blocks:         0
    base_depth:             4
    base_stack_filters:     [16, 32, 48]
    freeze_base:            False

data:
  type:           ScorePage
  root:           testPage/
  splits:         '*1,2,3,4,5,6,7,8/10:0/10'
  batch_size:     1
  args:
    trans:                    [HWC2CHW, Tar_STDgray, Tar_HWC2CHW]
    compound_labels:
      list:
        - label:              box_Staff
          channels:           [1]
        - label:              box_System
          channels:           [0, 1]
    augmentor:
      tinter:
        fore_pow:         6.
        fore_sigma:       0.2
        fore_scale_range: [40, 100]
        fore_blur_range:  [0, 1]
        back_pow:         8.
        back_sigma:       0.14
        back_scale_range: [0.02, 0.2]
        back_blur_range:  [0, 8]
      gaussian_noise:
        sigma:            0.01
      affine:
        padding_scale:    1.06
        angle_sigma:      1.
        scale_sigma:      0.2
        scale_mu:         0.6
        scale_limit:      1.
        size_limit:       780
      gaussian_blur:
        sigma:            0.6
      flip_mark:
        intensity_range:  [0, 0.1]
      distortion:
        scale:            2
        scale_sigma:      0.4
        intensity:        1.6
        intensity_sigma:  0.6
