
id:     peris/{date}-{filename}


data:
  type:                     SuperImage
  root:                     textures/coco2017 samples
  splits:                   '*1..8/10:9/10'
  batch_size:               1
  args:
    dimensions:             ./dimensions.csv
    cluster_size:           1228800
    downsample:             4


model:
  type:                     Reconstructor
  args:
    resolution_factor:      4
    layers:                 4
    num_res_blocks:         2
    dropout:                0.2
    loss_module:            lpips_alex_0.1.pt


trainer:
  device:         cpu
  save_mode:      best
  epoch:          2
  moniter:
    field:        loss
    mode:         min

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             1.e-3
      min_lr:             1.e-6
      decay_rate:         0.98
      n_warmup_steps:     10000
