
id:     score-topology/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

trainer:
  device:         cpu
  save_mode:      best
  epoch:          2

data:
  file_name:      test.zip
  splits:         '*1/3:2/3'
  batch_size:     1

model:
  type:           TransformSieveJointerH
  args:
    d_inner:              2048
    n_source_layers:      1
    n_target_layers:      1
    n_sieve_layers:       1
    n_head:               8
    d_k:                  64
    d_v:                  64
    dropout:              0.1
    scale_emb:            False

optim:
  type:                   Adam
  args:
    betas:                [0.9, 0.9999]
    eps:                  1.e-8
  scheduler:
    type:                 Exp
    args:
      lr_mul:             2.
      min_lr:             1.e-6
      decay_rate:         0.98
      n_warmup_steps:     4000
