
id:     score-topology/{date}-{filename}

env: ~
  #CUDA_VISIBLE_DEVICES: 0

trainer:
  device:         cpu
  save_mode:      best
  epoch:          2

data:
  file_name:      test.pkl
  splits:         '*1/3:2/3'
  batch_size:     1

model:
  type:           TransformJointerH_ED
  args:
    #d_model:              512  # determined by dataset
    d_inner:              2048
    n_source_layers:      1
    n_target_layers:      1
    n_head:               8
    d_k:                  64
    d_v:                  64
    dropout:              0.1
    scale_emb:            False

optim:
  lr_mul:             2.
  n_warmup_steps:     4000
