
id:     melody/{date}-{filename}


data:
  type:                     VocalPitch
  root:                     opencpop
  splits:                   '*1..92/100:93..99/100'
  batch_size:               4
  args:
    bias_limit:             0.3
    seq_align:              4
    augmentor:
      time_distortion:
        cycle:
          miu:                800
          sigma:              0.6
        amplitude:
          miu:                1.6
          sigma:              0.4
      offkey:
        cycle:
          miu:                60
          sigma:              0.6
        amplitude:
          miu:                6
          sigma:              0.6
      gain: ~
  args_variant:
    1:
      augmentor:
        time_distortion: ~
        offkey: ~
        gain: ~


model:
  type:                             VocalAnalyzer
  args:
    n_class:                        1
    encoder_dim:                    64
    num_down_layers:                2
    num_layers:                     6
    angle_cycle:                    1.e+5
    num_attention_heads:            8
    feed_forward_expansion_factor:  4
    conv_expansion_factor:          2
    input_dropout_p:                0.1
    feed_forward_dropout_p:         0.1
    attention_dropout_p:            0.1
    conv_dropout_p:                 0.1
    conv_kernel_size:               31
    half_step_residual:             True


trainer:
  device:                   cpu
  save_mode:                best
  epoch:                    2
  moniter:
    field:                  loss
    mode:                   min

optim:
  type:                     Adam
  args:
    betas:                  [0.9, 0.98]
    eps:                    1.e-9
  scheduler:
    type:                   InvSqrt
    args:
      lr_mul:               0.2
      n_warmup_steps:       400
      d_model:              256
